### ISSUE TITLE
ProductSubmission Join Table

### ISSUE THREAD

**Issue by beabout** [reedhersma/BCdjango#4]
I like the idea of creating a join table between `Products` and `Orders`

We could call it `ProductOrder`. The goal of this table is to tie a form submission to several products.

In `forms/models.py`, add 

```python
class ProductOrdermodels.Model):
    product = models.ForeignKey(Product)
    order = models.ForeignKey(Order)
```

### Reasoning 
- A form is available from the website for customers to place orders. 
- The customer can select one or more products in the form. 
- When submitting the form, a request is sent to the backend to create an **Order** object from the form's input
- In addition to the **Order** object, we can also create a **ProductOrder object for every product selected in the form. 
 
Then when we say Order.products, for that specific Order, it'll show us all the products! I can explain more another time.

**Comment by reedhersma** [comment]
Change to models.py should be pushed.
